### ISSUE TITLE
As a developer I want to download the sourcecode and build it from scratch without errors

### ISSUE THREAD

**Issue by MinnieTheMoocher** [nilsschmidt1337/ldpatterncreator#5]
Hi Nils, 

I just cloned your project from scratch and tried to build it inside Visual Studio 2013
(both Debug and Release build have this problem).

When opening the project and hitting build, I get
`
------ Build started: Project: LDPatternCreator, Configuration: Release Any CPU ------
D:\Projects\LDPatternCreator\LDPatternCreator\My Project\Resources.resx(246,5): error MSB3103: Invalid Resx file. Could not find file 'D:\Projects\LDPatternCreator\LDPatternCreator\bin\Release\lang\lang_de_DE.csv'. Line 246, position 5.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`
The file is present in a different folder, 
LDPatternCreator\ReleaseFiles\lang
, but there seems to be a custom build step missing which copies these files over.

The problem occurred for me with commit fab2a1892d4b0b1b0a6f941beb5dc20ac26cf33f

When trying to find the cause of the problem, I double clicked 
"My Project". Then the screen shown in the screenshot opens,
and another 3 error messages are issued:
`
Error	2	Invalid Resx file. Could not find file 'D:\Projects\LDPatternCreator\LDPatternCreator\bin\Release\lang\lang_de_DE.csv'. Line 246, position 5.	D:\Projects\LDPatternCreator\LDPatternCreator\My Project\Resources.resx	246	5	LDPatternCreator
Error	3	Resource 'lang_de_DE' could not be loaded because the file to which it is linked could not be found: D:\Projects\LDPatternCreator\LDPatternCreator\My Project\..\bin\Release\lang\lang_de_DE.csv.	D:\Projects\LDPatternCreator\LDPatternCreator\My Project\Resources.resx	0	0	
Error	4	Resource 'lang_en_GB' could not be loaded because the file to which it is linked could not be found: D:\Projects\LDPatternCreator\LDPatternCreator\My Project\..\bin\Release\lang\lang_en_GB.csv.	D:\Projects\LDPatternCreator\LDPatternCreator\My Project\Resources.resx	0	0	
Error	5	Resource 'lang_fr_FR' could not be loaded because the file to which it is linked could not be found: D:\Projects\LDPatternCreator\LDPatternCreator\My Project\..\bin\Release\lang\lang_fr_FR.csv.	D:\Projects\LDPatternCreator\LDPatternCreator\My Project\Resources.resx	0	0	
`

![lang files missing](https://user-images.githubusercontent.com/3216359/58354845-dc5d8a00-7e72-11e9-8eaa-15cbea300a66.png)

**Comment by nilsschmidt1337** [comment]
Closed with commit c169644.
